### PR TITLE
Remove icons from the repository

### LINKED ISSUE #44: Icon optimization - spaces around negatives?
The [README](https://github.com/godotengine/godot-design/blob/master/README.md) contains this section:

> Editor icons must be first optimized before being added to the engine, to do so:
> * Add them to the "/engine/icons/svg" folder.
> * Run the "optimize.py" script (you must have `scour` installed).

However, when I run `python3 optimize.py`, it results in over 300 changed files. Looking in my git client, it appears that they are all removals of spaces around negative numbers:

Zoomed in removal of spaces around negative decimal number

So, what's up with this? Is this intended behavior? If so, why aren't the fixed versions committed in the repository?

### LINKED ISSUE #52: Optimize icons with svgcleaner
@Calinou https://github.com/godotengine/godot/pull/32319

> Also, if this PR is merged, we should update instructions in godot-design to refer to svgcleaner instead of scour.

I noticed there wasn't an issue to track this.

### PR DESCRIPTION
**Pull request by Calinou**
Optimized icons are already available in the main Godot repository. Unoptimized SVG icons aren't very useful to keep around, as the information lost by the optimization (coordinate rounding) isn't visible to the naked eye.

Original PNG icons from the Godot 2.x era are no longer relevant. They can still be fetched from the Godot repository's `2.1` branch if needed.

*Bugsquad edit:* Closes #44, closes #52

### CODE REVIEW

**Comment by Xrayez** [comment]
Aren't unoptimized SVG icons useful for those who would want to build upon or enhance the existing icon design? I mean, what happens when you modify *optimized* icon, and then have to optimize it again? Would that somehow worsen the quality further?

**Comment by Calinou** [comment]
> I mean, what happens when you modify optimized icon, and then have to optimize it again? Would that somehow worsen the quality further?

If you optimize the same SVG with `--multipass` multiple times, you'll always get the same result, so that shouldn't be an issue.

**Comment by fire** [comment]
Are there remaining items? I'll merge this after the response.

**Comment by fire** [comment]
> <Akien> Sure. I don't mind so much what happens on godot-design to be fair, I don't have much bandwidth for it.

Thanks!

**Comment by LikeLakers2** [comment]
Apologies for the bump, but I figure I should ask. The Godot repository doesn't list any specific license for the editor icons, and as best as I can tell, this repository labeled the editor icons as CC-BY 4.0 before their removal.

Would the editor icons still be usable under CC-BY 4.0?

And in any case, could their license be added to the `COPYRIGHT.TXT` file in the Godot repository?

**Comment by fire** [comment]
I think so. Want to make a pr for that?

**Comment by LikeLakers2** [comment]
@fire My apologies, but to be honest, I'm not actually sure I feel comfortable doing so, as it relates to copyright. This is something I'd prefer that a Godot team member do, as it seems that the Godot team has a better grasp on Godot's copyright situation than I do.

But even if I was comfortable, there's a couple issues:

1. Are you sure they're CC-BY 4.0? Because if you aren't, then I can't take your word for it.
2. Who would I attribute the copyright to? Would `2007-2021, Juan Linietsky, Ariel Manzur. 2014-2021, Godot Engine contributors.` fit?

**Comment by akien-mga** [comment]
> Apologies for the bump, but I figure I should ask. The Godot repository doesn't list any specific license for the editor icons, and as best as I can tell, this repository labeled the editor icons as CC-BY 4.0 before their removal.

The editor icons in the engine repository are under the MIT license, like the engine itself. They're covered by the main globbing pattern here: https://github.com/godotengine/godot/blob/master/COPYRIGHT.txt#L44-L48

**Comment by LikeLakers2** [comment]
@akien-mga Are you sure? Because I thought stuff like editor icons would have to be covered by CC licenses (just like the logo is), not by a license meant for code.

**Comment by akien-mga** [comment]
It's customary to use CC licenses for art but not a requirement. These icons are an integral part of Godot which is MIT licensed, so they can be licensed the same, even if MIT is better suited for source code than images (but SVGs are also "source" like e.g. the documentation XMLs or other kind of text based metadata).

**Pull request merged**
