### PR TITLE
Update readme screenshots for 4.3

### PR DESCRIPTION
**Pull request by tetrapod00**
Resolves https://github.com/godotengine/godot/issues/95761.

Screenshots taken on Windows 10.

I imported the master (4.x) branch of the TPS demo and moved some things around to match the old screenshot. I also turned on SSAO, SSIL, SDFGI, Volumetric Fog, and Glow on mostly default settings. Unfortunately, the particles on the core don't look like 3.5beta anymore. I tried turning up the max number of particles on each emitter but it didn't help.

I used self-contained mode, so this should be the default editor look on Windows 10 Godot 4.3.

The 1080 JPG was created by exporting the raw 1080 PNG screenshot at ~90% quality from Krita, to match the existing filesize.

For the 4K screenshot, I set DSR to 4x (3840 x2160) on my NVIDIA GeForce GTX 1660. I set the editor scaling to 100% - apparently Godot does not need the editor scaling changed for higher resolutions, at least with the DSR setup I used.

### CODE REVIEW

**Comment by Calinou** [comment]
> For the 4K screenshot, I set DSR to 4x (3840 x2160) on my NVIDIA GeForce GTX 1660. I set the editor scaling to 100% - apparently Godot does not need the editor scaling changed for higher resolutions, at least with the DSR setup I used.

Unfortunately, the screenshot you included looks like a 1080p screenshot with 2× nearest-neighbor scaling. It's not an actual hiDPI screenshot.

**Comment by tetrapod00** [comment]
It's a bit of work to set up the project so it looks the same as the 3.5 version, so I'll try again. I missed the step of setting *windows* scale.

**Comment by tetrapod00** [comment]
Final steps that worked for me:
- Turn on DSR 4x. DSR smoothing was set to 50% (as I understand it, this shouldn't affect the outcome, only what displays on the 1080 screen.)
- Set one 1080 monitor to 4K in windows display settings.
- In windows settings, `Display -> Scale and Layout -> Advanced scaling settings`. Uncheck `Let Windows try to fix apps so they're not blurry`. Set custom scaling to 200%.
- Log out. Log in.
- Set Godot editor scale to 200% (`Editor -> Editor Settings... -> Interface -> Editor -> Display Scale`).
- Take screenshot.

**Comment by tetrapod00** [comment]
The particle effect downgrade was bothering me. I double checked and found that there was an actual VFX hidden underneath the orange sphere. Also made some tweaks to WorldEnvironment.

Now I'm happy with these screenshots as a representation of Godot 4.3.

**Review by Calinou — APPROVED** [review]
Looks great!

I force-pushed a commit that optimizes the PNG losslessly to bring its size closer to what it was in 3.x.

**Comment by tetrapod00** [comment]
Thanks for your patience with the upscaling!

**Comment by coppolaemilio** [comment]
thanks!

**Pull request merged**
