### PR TITLE
Reorganize everything

### PR DESCRIPTION
**Pull request by groud**
I reorganized the folders so it is a little bit clearer where everything is :)

### CODE REVIEW

**Comment by akien-mga** [comment]
Fine by me, I'll let @djrm review.

**Comment by djrm** [comment]
i would change:
software-design -> engine
move business cards  to  communication
Avoid personal content (Akien cards for example)

**Comment by groud** [comment]
Ah yeah, "engine" is better.
Ok for the rest too.

**Comment by groud** [comment]
done :)

**Comment by groud** [comment]
Done :)

**Pull request merged**
