### PR TITLE
Added 2018 assets

### LINKED ISSUE #9: Banner/poster for GodotCon 2018
We're going to announce GodotCon 2018 which will take place in Brussels, Belgium on 5 & 6 February, and it would be nice to have a specific banner/poster design that we could use in the announcement blog post, on the events page, etc.

For [GodotCon 2017](https://godotengine.org/article/meet-us-fosdem-2017-and-godotcon), @razvanc-r had made this one:
587f626da0f7f646960937
[GodotCon 2017 SVGs.zip](https://github.com/godotengine/godot-design/files/1535606/GodotCon.2017.SVGs.zip)

For [Meet the Nodes](https://godotengine.org/article/meet-nodes-godot-event-paris) in Paris last Spring I had made this one:
58da19bd70642796203728
[MeetTheNodes 2017 SVG.zip](https://github.com/godotengine/godot-design/files/1535613/MeetTheNodes.2017.SVG.zip)

It would be good to have something good looking for GodotCon 2018, which seems both friendly and professional. We don't have much time (I would like to post about GodotCon ASAP, actually tonight :D), so for the first iteration it could be kept simple like the GodotCon 2017 artwork, and maybe improved later on.

For info, the font used in the Godot logo and in the first image for "GODOTCON" is Lilita One.

(*) I doubt we can have something done by tonight, so I might go for a non-descript Godot 3.0 screenshot for this first blog post. There will be other posts in coming weeks to give more info about the venue we'll have selected, the talks that will be held, etc., so we'll be able to use the official artwork then.

### LINKED ISSUE #10: Merchandise design for FOSDEM / GodotCon
[FOSDEM and GodotCon 2018](https://godotengine.org/article/get-ready-fosdem-and-godotcon-2018) are coming in less than two months (7 weeks actually from now), and there are various merch stuff we'd like to have for the events that will require some design work.

Current ideas of things we'd like to print are listed below. Not everything *must* be done though.

- T-shirts. We already have a design from last year based on @djrm's node icons, but the Godot logo changed in the meantime, some icons changed too, and maybe we want to go for something different? Here's the source of the previous/current design: 
[Godot T-shirt 2017 - Nodes.zip](https://github.com/godotengine/godot-design/files/1558863/Godot.T-shirt.2017.-.Nodes.zip). It looks [like this](https://godotengine.org/storage/app/uploads/public/5a2/678/7be/5a26787bebf13417068091.jpg).
We still have ~40 T-shirts with that design that we'll sell for a bargain, but we need a cool new one for this year.
- Stickers: Plain rectangular sticker with Godot logo + name, or detoured with only the logo (head), or something based on the same design as the T-shirt? Someone needs to check for the print details so that we know what are the constraints for the design, but we can start sharing design ideas.
- Business cards: Godot-themed business card for the engine itself, with contact address, website, etc. Maybe also business cards for prominent devs based on the same design? (Not sure about the last one, usually business cards are bought by hundreds, so it could be a lot to print and hard to define who gets one)
- Flyers: A5 sheet with the most important information about Godot, links, etc., so that people can take them home and check Godot after FOSDEM.
- Mugs: Godot-themed coffee mugs would be nice to sell. I'd love to have one myself :P
- Kakemono/banner: We already have a nice one from last FOSDEM, since it's quite expensive and big I think we'll stick with that one for now, even though the logo is outdated.
- Other ideas you may have

We need to go fast, as printing and delivery takes time, so we should likely order stuff beginning of January at the latest. So please make design proposals ASAP so that we can work on the logistics afterward.

### PR DESCRIPTION
**Pull request by djrm**
i created a couple of assets for the godot style and design material for 2018.

ping @akien-mga, @groud, @reduz

closes #9 
closes #10 

**Business cards**

business-card-front

business-card-back

**godotcon banner**
godot_con_banner_2018

**Godotcon poster (in case you want to print some, you better do)**
godot_con_poster_2018

**godot tshirt**
godot_tshirt_2018

thats all folks.

### CODE REVIEW

**Comment by reduz** [comment]
Wow, looks amazing

**Comment by akien-mga** [comment]
Simply awesome :)

That GodotCon banner is just what I needed to finally motivate myself to write the Call for Participations on the blog :D

**Comment by akien-mga** [comment]
Merging as is, feedback and tweaking of each asset/motif can be discussed in separate issues.

**Comment by groud** [comment]
Yes, they are beautilful :D

**Comment by NathanLovato** [comment]
Great work indeed! Akien asked me to give some feedback. There's little to say, overall it works very well.

I assume the business card designs are for 2 individual pieces and not the 2 sides of the same one? Otherwise the design would feel redundant, busy and the two slightly different background colors weird.

Aside from that the banner design is off balance with the logo and Free entry text with the stars. Could use a slight offset.

And the last nit-pick: the mono font on the shirt design is out of place to me. It doesn't integrate well with the modern feel of the shapes and the logo's font around it. I'd remove the url, move some stars up and scale the globe/web icon along with the stroke that connects it to the central part.

**Comment by djrm** [comment]
@NathanLovato  yeah, today that i see it again i think there could be some improvements (that of course i will make), im thinking about cleaning the business card front, trying other colors for the shirt design, and yeah as you point out there is some balancing that needs to be done (i wasnt seeing it yesterday). thanks for the feedback

any other person wants to comment something... im accepting changes right now.

**Comment by djrm** [comment]
alright i made some improvements for the 2018 assets, 43596b0387bfaaf621469c7c1d29f6e8e7a9498f, nice diff there.

**Comment by groud** [comment]
I felt the square on the middle  of the t-shirt design a little bit like stifling on the main logo. So I did a quick edit (on the previous version) so that Gobot's head is a little bit bigger and highlighted:

894392quicktest

Else all the changes in your diff are good improvements to me, the cards seems way better. :)

**Comment by akien-mga** [comment]
Awesome changes @djrm. I would just remove the "3.0" in the flag, as it will be obsolete in a few months, so it's maybe better to keep it out and make sure we can continue using this T-shirt proudly in the ages :)

**Comment by toger5** [comment]
@djrm really nice work. (for the t-shirt poster...) I really like the direction you are pushing the branding/design of godot engine. It is a beautiful and good direction. (also for the ui/icons!!!)

I actually kind of like the 3.0 it is sooo tiny and kind of like a little fun easter egg (in a couple of years)
it's also a nice reminder since 3.0 will be a really big game changing release.
So I would love to have it on my shirt even if it is indeed outdated soon.

**Comment by djrm** [comment]
@akien-mga that shirt will be a reminded of this particular year, next release i will make something different / better?... who knows.

**Comment by akien-mga** [comment]
> I actually kind of like the 3.0 it is sooo tiny and kind of like a little fun easter egg (in a couple of years)
it's also a nice reminder since 3.0 will be a really big game changing release.
So I would love to have it on my shirt even if it is indeed outdated soon.

Fair enough :)

**Comment by akien-mga** [comment]
@djrm Could you make a variant of the business card for Godot "staff"? I'd like to get a set printed for myself (Rémi Verschelde (Akien), Project Manager, remi @ godot's_domain).

**Comment by djrm** [comment]
@akien-mga i think i can post an alternative SVG, so you can edit that with your info

**Comment by djrm** [comment]
@akien-mga ok, it's up, you will need the Montserrat font semi-bold and bold variations + inkscape.

https://github.com/godotengine/godot-design/blob/master/assets/2018/business-card-back-member_2018.svg

**Comment by akien-mga** [comment]
Perfect, thanks!

**Comment by akien-mga** [comment]
I think it might be worth replacing the phone number by a GitHub logo + `@john_doe`.

**Comment by akien-mga** [comment]
+ maybe optionally next to it Twitter logo (also monochrome of course) + handle?

**Comment by akien-mga** [comment]
Here's my take on it: 
[business-card-back-akien_2018.zip](https://github.com/godotengine/godot-design/files/1629721/business-card-back-akien_2018.zip)
business-card-back-akien_2018

**Comment by djrm** [comment]
@akien-mga looks nice, but i wonder how it will be for people with longer user names.

**Comment by groud** [comment]
So @akien-mga , should I order some for you ?
Also, maybe you want yours @reduz ?

**Comment by akien-mga** [comment]
@djrm Those can remove the Twitter part, or make things smaller as need be.

@groud Yes please :D

**Comment by groud** [comment]
BTW the actual svg size is wrong for business cards (maybe its the french format)
It should be 85 x 55 mm.

**Comment by groud** [comment]
The modified version for a 85 x 55mm card
business-card-back
business-card-back-akien
business-card-front

**Pull request merged**
