### PR TITLE
Adds a business card design and other stuff

### PR DESCRIPTION
**Pull request by groud**
Do not merge yet, the design are open to discussion:

Front:
front
or a variant:
front

Back:
back

WDYT ?

### CODE REVIEW

**Comment by djrm** [comment]
ok, i made some proposals, they are also open for discussion (i took some ideas from @groud 's design)

FRONT
business-card-front

BACK
business-card-back svg

**Comment by djrm** [comment]
and here it is a godot render for simulation purposes

screenshot from 2017-12-17 19-49-22

**Comment by groud** [comment]
I'll try with bigger icons on mine too, it looks better :)

**Comment by groud** [comment]
Updated with new design :)

**Comment by djrm** [comment]
@groud here are the svgs. if you want to make other mockups.

[godot-business-card.zip](https://github.com/godotengine/godot-design/files/1569640/godot-business-card.zip)

**Comment by djrm** [comment]
business-card-back svg_h

**Comment by toger5** [comment]
I like them.
Still want to post my opinions:
I dont like the grey shadow. But the white bg is cool. Just the grey shadow is weired.
I also do like the back from @groud. If there would be a little less information. Remove modern multiplat....
And the join the community part.
Djrm s is nice i dont know what to think about the godot in the suit idea. This makes me associate godot with a financially orientated business. And i also prefer the light front.

**Comment by groud** [comment]
I updated the design. WDYT ?

**Comment by djrm** [comment]
@groud i think it is better (at least the back), but now both sides look very unrelated, in the front you have a colorful (party like colors) background with gradients and all that, and in back you have a very flat and more sober design so both sides do not match (besides the back grid problems, but i understand it is a mockup), so i dont mind if the front is light or dark but both part have to be consistent with each other.

**Comment by groud** [comment]
I updated the design. I added a little bit of color to the back, but I wanted it to stay subtle. Having a contrast between the back and the front is better, IMHO.

I tested to add black in the corners of the front, but I'd prefer using the full white one, also for having a contrasted front/back.

**Comment by kubecz3k** [comment]
I like the most current Groud 'variant' + back idea. Also not sure about that 'Godot in suit' idea, but I noticed that djrm preview was rendered in Godot editor itself which is (and looks) super neat! :)

**Comment by bojidar-bg** [comment]
I think I fully agree with kubecz3k on that.

**Comment by kubecz3k** [comment]
However I must say that Djrm's front + Groud's back is also a neat combination.

**Comment by akien-mga** [comment]
I tend to prefer @groud's Front (or Variant, not sure) + Back, mostly because it's more colourful and that's an important feature of Godot IMO (colourful, friendly logo - easy to use. But still professional with a clean design).

Not sure about centering the "Game engine" text below "GODOT", it's left-aligned in the official logo so maybe better to keep as is? Unless it looks bad ;)

The "Join the community" icons are a bit crowded, but it's also nice that it adds some colour. Since it's printed, it doesn't help users much to see those without being able to click them, but at least they know they exist :P
The IRC icon doesn't look so familiar to me, is it a standard icon? If we want something more "useful", a link to godotengine.org/community would be good, as that's where they will find all the needed info. (We have a link to godotengine.org, but from there people have to know that there's a community menu entry which will give them the info they need)

**Comment by reduz** [comment]
@djrm Can you try the following changes to your design? just for tests..

On the back, have the godot icons colored, more similar to the facebook group banner. I think its more trendy now.

On the front, as it is is fine, but I would use all over a white background, instead of the white/black split.

**Comment by reduz** [comment]
@djrm Also on the back, just the godot icon i think should be enough, no need to repeat the Godot Engine text on both sides.

**Comment by reduz** [comment]
For reference, I am using these:
image

**Comment by djrm** [comment]
the issue with too much color for backgrounds, is that it steals the focus (which in this case is quite important), backgrounds are just to fill the space (a detail) not to be the main point of atention. also my main complaints about the grouds design are the same as before (maybe im a bit picky but...)

1- lack of geometric consistency (look at the triangles at front)
2- lack of overall stylistic consistency (front and back styles are very different in style)
3- the colors used for the icons, to me the card front looks like a party invitation... (maybe intended? "join the godot party"...)
4- there are no consistent margins and the back is really crowded.

but at the end i doubt most people will see those details (if they are even relevant), thats just my opinion.

i will try some variations today... and post them, if i cant do them go ahead with the one you (the people who will print them) like like better.

**Comment by groud** [comment]
Ok if you're going to work a little bit more on those. Here's some feedback from the IRC:
- Please remove the Godot in suit, it is too much like a "private joke" of the community.
- It would be good to make the design a little bit less "businessy". @akien-mga described the idea correctly "I mean we do want to appear as a professional solution that rivals proprietary engines, but the fact that we're an open source tool developed by a friendly community of passionate users is our key feature." => It has to look more "friendly", I would say (that's why I added the color originally, but if there's another way to do it that would be cool).

**Comment by djrm** [comment]
ok, here is a new concept more colorful

business-card-front

feedback on the concept please, so we can close this chapter, im willing to work on this and other material today, so the more feedback, the better

**Comment by djrm** [comment]
ok will remove the business godot, @groud you know that i wasnt even planning to put it there, i did it because of you :)

screenshot from 2018-01-07 12-39-32

**Comment by groud** [comment]
Nice, I like it a lot ! Can you try with the logo a little bit bigger, to see how does it looks like ?
Also there's no margin around the card, part of the nodes might be removed when the cards will be cut (I don't know if it matters in your design).

Arf, this poor Godot in suit will find another job I'm sure ^^

**Comment by djrm** [comment]
update, added back, with a little graphic that represents the community. @groud im not sure margin is needed, so you say that the image im posting wont get completely printed?

font
business-card-front

back
business-card-back

**Comment by groud** [comment]
The back is nice too :) I would change the font though.

> so you say that the image im posting wont get completely printed ?

Well usually, whatever you print, the margin might move around 1 mm due to the way things are printed. So it's better not to put details on the surrounding unless it does not matter if they are cut a little bit.

**Comment by groud** [comment]
> no problem with the cut as long as it is uniform across all the sides (because of the designed margins).

This is usually not guaranteed :/

**Comment by djrm** [comment]
@groud seems like vistaprint likes 92x54mm (a bit wider) and they specify the safe zone, so it might be a good idea to go for that size, with the specified safe zone.

**Comment by groud** [comment]
Sure :)

**Comment by akien-mga** [comment]
Closing as superseded by #13, though there are some nice ideas here if we want to make alternative designs for fun (but we should settle on a small set of "main" designs for all official stuff, and use the alternative ones only for private or internal stuff).

**Pull request closed without merging**
