### PR TITLE
added spring arm node icon

### PR DESCRIPTION
**Pull request by QbieShay**

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Doesn't appear to have a optimized version of the icon, do you have "scour" installed?

**Comment by QbieShay** [comment]
@YeldhamDev I do, but doesn't look like it's working? I'm on windows :(

**Comment by YeldhamDev** [comment]
What's the output once you run the script?

**Comment by QbieShay** [comment]
None :<

**Comment by YeldhamDev** [comment]
Does the `scour` version matches the Python one (there is one for 2.7.* and for 3.7.*)?

Make sure to remove the spring arm icon, run it, put it back, then run it once more, and see if there's still no input.

**Comment by QbieShay** [comment]
This is my outputafter the steps you suggested.
``` 
 File ".\optimize.py", line 108, in <module>
    with open('{}/{}.svg'.format(svgs_path, name_only), 'r') as svgo:
FileNotFoundError: [Errno 2] No such file or directory: 'svg/desktop.ini.svg'
```

**Comment by YeldhamDev** [comment]
Wait, why was there a file named "desktop.ini.svg" in the "svg" folder?

**Comment by QbieShay** [comment]
@YeldhamDev i quit trying on windows, but also on Linux it does not generate the optimized svg.
What i did was make the spring arm icon svg then put it in the svg folder then ran the script. Am I missing something?

**Comment by QbieShay** [comment]
I also see that in #30 the optimized version is missing

**Comment by QbieShay** [comment]
It came kind of late but I finally did it!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
