### PR TITLE
Add banner that will be used for discourse

### PR DESCRIPTION
**Pull request by winston-yallow**

### CODE REVIEW

**Comment by YuriSizov** [comment]
You should probably optimize it with SVGCleaner or SVGO.

**Comment by winston-yallow** [comment]
> You should probably optimize it with SVGCleaner or SVGO.
Good idea, done!

**Comment by winston-yallow** [comment]
This now has dark and light mode versions of the banner, placed in a new subfolder for discourse. Both SVGs are optimized via `svgo`

**Comment by YuriSizov** [comment]
Oops, should've merged long ago :) Thanks!

**Pull request merged**
