### PR TITLE
Added noise texture icon

### PR DESCRIPTION
**Pull request by qonnop**
See issue https://github.com/godotengine/godot/issues/22704
By running the optimize script, several other icons were also optimized/reformatted and hashes changed.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by LikeLakers2** [comment]
Wait, does this actually make the icon show next to "New NoiseTexture"? I thought there was more to it than just adding an icon...

**Comment by qonnop** [comment]
The Scons build system generates a header file from all SVG files in the editor/icons folder of godotengine. It's fully automatic.

**Comment by LikeLakers2** [comment]
Ah... alright. Thanks for clarifying.

**Pull request merged**
